site_name: Envoy Gateway Fundamentals
theme:
  name: material
  logo: assets/tetrate-logo-white.png
  palette:
    primary: purple
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
#    - navigation.tabs
    - navigation.expand
    - content.code.annotate
    - content.code.copy
nav:
  - index.md
  - setup.md
  - getting-started.md
  - shared-gw.md
  - https.md
  - retries.md
  - ratelimit.md
  - Security:
    - auth.md
    - ext-authz.md
    - oidc.md
  - Traffic management:
    - traffic-split.md
  - Extensibility:
    - wasm.md
  - Observability:
    - observability.md
  - takeaways.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: artifacts
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.smartsymbols
  - toc:
      permalink: true
plugins:
  - search
  - macros # https://mkdocs-macros-plugin.readthedocs.io/en/latest/
extra:
  eg:
    version: 1.1.0
